# Generated by Django 3.2.6 on 2021-08-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
    ]
