# Generated by Django 3.2.6 on 2021-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_descriptions_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
