# Generated by Django 3.2.6 on 2021-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210813_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('gas', 'gas'), ('electric', 'electric')], max_length=10, null=True),
        ),
    ]
