# Generated by Django 3.2.6 on 2021-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
