# Generated by Django 3.2.6 on 2021-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extras',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
